"use client"
import type { PlayerData } from "@/lib/types"
import { PlayerAvatar } from "@/components/ui/PlayerAvatar"
import { usePlayerData } from "@/context/PlayerDataProvider"

/**
 * Shareable preview card with personalized styling
 */

interface SharePreviewProps {
  playerData: PlayerData
}

export function SharePreview({ playerData }: SharePreviewProps) {
  const { personaTheme } = usePlayerData()
  const accentColor = personaTheme?.accentColor || "var(--accent-gold)"

  return (
    <div
      id="share-preview"
      className="relative mx-auto w-full max-w-2xl overflow-hidden rounded-2xl p-8"
      style={{
        background: `linear-gradient(135deg, var(--bg-900) 0%, var(--bg-800) 100%)`,
        border: `2px solid ${accentColor}`,
      }}
    >
      {/* Background vignette */}
      <div
        className="absolute inset-0 opacity-20"
        style={{
          background: `radial-gradient(circle at top right, ${accentColor}, transparent 70%)`,
        }}
      />

      {/* Content */}
      <div className="relative z-10">
        {/* Header */}
        <div className="mb-6 text-center">
          <div className="text-5xl font-bold text-white">
            <span style={{ color: accentColor }}>RIFT</span>REVIEW
          </div>
          <div className="mt-2 text-sm text-[var(--muted-gray)]">AI-Powered Game Analysis</div>
        </div>

        <div className="mb-6 flex flex-col items-center gap-4">
          <PlayerAvatar
            src={playerData.profilePicture}
            alt={playerData.displayName}
            size="lg"
            showRankBadge
            rank={playerData.rank}
          />

          <div className="text-center">
            <h2 className="text-3xl font-bold text-white">{playerData.displayName}</h2>
            <div className="mt-1 text-sm font-semibold text-[var(--muted-gray)]">{playerData.rank}</div>
            <div
              className="mt-2 inline-flex items-center gap-2 rounded-full px-4 py-1"
              style={{ backgroundColor: `${accentColor}20`, border: `1px solid ${accentColor}` }}
            >
              <div className="h-2 w-2 rounded-full" style={{ backgroundColor: accentColor }} />
              <span className="text-sm font-bold text-white">{playerData.mainRole}</span>
            </div>
          </div>
        </div>

        {/* Stats grid */}
        <div className="mb-6 grid grid-cols-3 gap-4">
          {playerData.highlights.map((highlight) => (
            <div key={highlight.stat} className="rounded-xl bg-[var(--glass)] p-4 text-center backdrop-blur-sm">
              <div className="text-2xl font-bold text-white">{highlight.value}</div>
              <div className="mt-1 text-xs text-[var(--muted-gray)]">{highlight.stat}</div>
            </div>
          ))}
        </div>

        <div className="rounded-xl bg-[var(--glass)] p-4 text-center backdrop-blur-sm">
          <p className="text-sm font-semibold text-white">{personaTheme?.tagline || playerData.personality}</p>
        </div>

        {/* Footer */}
        <div className="mt-6 text-center text-xs text-[var(--muted-gray)]">Generated by RiftReview • riftreview.gg</div>
      </div>

      {/* Decorative elements */}
      <div
        className="absolute -bottom-10 -right-10 h-40 w-40 rounded-full opacity-30 blur-3xl"
        style={{ backgroundColor: accentColor }}
      />
      <div
        className="absolute -left-10 -top-10 h-40 w-40 rounded-full opacity-20 blur-3xl"
        style={{ backgroundColor: accentColor }}
      />
    </div>
  )
}
